######################################################################
# Automatically generated by qmake (2.01a) Mon May 3 16:04:28 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ui_MainWindow.h
SOURCES += main.cpp
