######################################################################
# Automatically generated by qmake (2.01a) Mon May 3 16:37:16 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += MyOtherMainWindow.h ui_MainWindow.h
SOURCES += main.cpp MyOtherMainWindow.cpp
