######################################################################
# Automatically generated by qmake (2.01a) Mon May 3 16:43:39 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += MyAutoMainWindow.h ui_MainWindow.h
SOURCES += main.cpp MyAutoMainWindow.cpp
