fork: fork.c useful_functions.c
	gcc -Wall fork.c useful_functions.c -o fork -g

threads: threads.c useful_functions.c
	gcc -Wall threads.c useful_functions.c -o threads -g

raceCondition: raceCondition.c useful_functions.c
	gcc -Wall raceCondition.c useful_functions.c -o raceCondition -g
